baseURL = 'https://www.shorette.dev/'
languageCode = 'en-us'
title = 'Carmine Shorette'
theme = 'typo'

[params]
# Appearance
theme = 'dark'

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = 'Hello! ðŸ‘‹'
homeIntroContent = """
Currently studying Applied Math and CS at [UWâ€“Madison](https://www.wisc.edu).

This summer, I'm working as a Middleware Development Intern at the [Department of Employee Trust Funds](https://etf.wi.gov/).

In my free time, I enjoy tinkering with Linux systems (I use Arch BTW) and playing chess.

Lately, I've been obsessed with building option pricing models. Twitter DMs always open!
"""

# Collection to display on home page: 
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

breadcrumbs = true

# Social icons
[[params.social]]
name = "email"
url = "mailto:Carmine@Shorette.dev"

[[params.social]]
name = "github"
url = "https://github.com/ItsCarmine"

[[params.social]]
name = "leetcode"
url = "https://leetcode.com/u/JavaBrewed/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/carmine-shorette/"

[[params.social]]
name = "x"
url = "https://twitter.com/0xTaka_"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "resume"
url = "/pdf/Carmine_Shorette_Resume.pdf"